apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: zremal
spec:
  master:
    # basePlugins:
    # - name: kubernetes
    #   version: 1.18.3
    # - name: workflow-job
    #   version: "2.34"
    # - name: workflow-aggregator
    #   version: "2.6"
    # - name: git
    #   version: 3.12.0
    # - name: job-dsl
    #   version: "1.76"
    # - name: configuration-as-code
    #   version: "1.47"
    # - name: kubernetes-credentials-provider
    #   version: 0.12.1
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:2.263.2-lts-alpine
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator
    targets: "jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/nicosto/jenkins-seed.git