apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: slim
spec:
  master:
    image: jenkins/jenkins:lts
  seedJobs:
  - id: jenkins-operator
    targets: "jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/nicosto/jenkins-seed.git