apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: jenkins-operator
spec:
  master:
    basePlugins:
    - name: kubernetes
      version: 1.29.0
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: 4.6.0
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.47"
    - name: kubernetes-credentials-provider
      version: "0.16"
    containers:
      image: jenkins/jenkins:2.263.4-lts-alpine
      imagePullPolicy: Always
    plugins:
    - name: prometheus
      version: 2.0.8
    - name: credentials
      version: 2.3.15
    - name: plain-credentials
      version: "1.7"
    - name: dependency-track
      version: 3.1.0
    - name: pipeline-utility-steps
      version: 2.6.1
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
    volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: jenkins-backup
  seedJobs:
  - additionalClasspath: ""
    bitbucketPushTrigger: false
    buildPeriodically: ""
    description: Jenkins Operator repository
    failOnMissingPlugin: false
    githubPushTrigger: false
    id: jenkins-operator
    ignoreMissingFiles: false
    pollSCM: ""
    repositoryBranch: main
    repositoryUrl: https://github.com/nicosto/jenkins-seed.git
    targets: jobs/*.jenkins
    unstableOnDeprecation: false
