apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-zremal-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jenkins-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: zremal/operator
    repoURL: https://github.com/nicosto/jenkins
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true