apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dependency-track
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dependency-track
  project: default
  source:
    chart: dependency-track
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - host: dtrack.k3s.zremal.org
              paths:
                - "/"

    repoURL: https://evryfs.github.io/helm-charts/
    targetRevision: 1.0.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true