apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dependency-track
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dependency-track
  project: default
  source:
    chart: dependency-track
    helm:
      values: |
        frontend:
          replicaCount: 1
          env:
            - name: API_BASE_URL
              value: ""
            - name: ALPINE_DATABASE_MODE
              value: "external"
            - name: ALPINE_DATABASE_URL
              value: "jdbc:postgresql://postgresql.pg.svc:5432/deptrack"
            - name: ALPINE_DATABASE_DRIVER
              value: "org.postgresql.Driver"
            - name: ALPINE_DATABASE_USERNAME
              value: "deptrack"
            - name: ALPINE_DATABASE_PASSWORD
              value: "deptrack"
        # ingress:
        #   enabled: true
        #   host: dt.k3s.zremal.org
        postgresql:
          enabled: false
    repoURL: https://evryfs.github.io/helm-charts/
    targetRevision: 1.0.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true