apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dependency-track
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dependency-track
  project: default
  source:
    repoURL: https://evryfs.github.io/helm-charts
    chart: dependency-track
    targetRevision: 1.0.5
    helm:
      values: |
        ingress:
          enabled: true
          tls:
            enabled: false
            secretName: ""
          annotations: {}
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
            ## allow large bom.xml uploads:
            # nginx.ingress.kubernetes.io/proxy-body-size: 10m
          host: dt.k3s.zremal.org

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true