apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dependency-track
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dependency-track
  project: default
  source:
    chart: dependency-track
    # helm:
    #   values: |
    #     postgresqlDatabase: metrics
    #     metrics:
    #       enabled: true
    #       serviceMonitor:
    #         enabled: true
    #         additionalLabels:
    #           release: prometheus-grafana
    repoURL: https://evryfs.github.io/helm-charts/
    targetRevision: 0.2.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true