apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  master:
    # basePlugins:
    # - name: kubernetes
    #   version: 1.18.3
    # - name: workflow-job
    #   version: "2.34"
    # - name: workflow-aggregator
    #   version: "2.6"
    # - name: git
    #   version: 3.12.0
    # - name: job-dsl
    #   version: "1.76"
    - name: configuration-as-code
      version: "1.47"
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-operator
  project: default
  source:
    chart: jenkins-operator
    repoURL: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart
    targetRevision: 0.4.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true