apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  project: default
  source:
    chart: jenkins
    helm:
      values: |
        controller:
          additionalPlugins:
            - prometheus:2.0.8
            - credentials:2.3.15
            - plain-credentials:1.7
            - dependency-track:3.1.0
            - pipeline-utility-steps:2.6.1
            # - gitea:1.2.1    # jenkins is crashing when enabled 
          ingress:
            enabled: true
            hostName: jenkins.k3s.zremal.org
          prometheus:
            enabled: true
            serviceMonitorAdditionalLabels:
              release: prometheus
          adminPassword: admin
    repoURL: https://charts.jenkins.io
    targetRevision: 3.1.9
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true