apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-operator
  project: default
  source:
    chart: jenkins-operator
    repoURL: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart
    targetRevision: 0.4.2
    helm:
      values: |
        jenkins:
          namespace: jenkins-operator
          image: jenkins/jenkins:2.263.4-lts-alpine
          basePlugins:
            - name: kubernetes
              version: "1.29.0"
            - name: workflow-job
              version: "2.40"
            - name: workflow-aggregator
              version: "2.6"
            - name: git
              version: "4.6.0"
            - name: job-dsl
              version: "1.77"
            - name: configuration-as-code
              version: "1.47"
            - name: kubernetes-credentials-provider
              version: "0.16"

          plugins:
            - name: prometheus
              version: "2.0.8"
            - name: credentials
              version: "2.3.15"
            - name: plain-credentials
              version: "1.7"
            - name: dependency-track
              version: "3.1.0"
            - name: pipeline-utility-steps
              version: "2.6.1"

          seedJobs:
            - id: jenkins-operator
              targets: "jobs/*.jenkins"
              description: "Jenkins Operator repository"
              repositoryBranch: main
              repositoryUrl: https://github.com/nicosto/jenkins-seed.git

          configurationAsCode:
            jenkins:
              systemMessage: |
                Welcome to this build server.

                This Jenkins is 100% configured and managed 'as code'.
                Config is now mostly handled by the 'Jenkins Configuration as Code' (JCasC) plugin.

            unclassified:
              location:
                url: http://jenkins.k3s.zremal.org:8080/
                jenkinsAdminEmail: cicd@zremal.org

# credentials:
#   system:
#     domainCredentials:
#       - credentials:
#           - string:
#               scope: GLOBAL
#               id: slack-token
#               secret: "${SLACK_TOKEN}"
#               description: Slack token

          backup:
            enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true