apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-operator
  project: default
  source:
    chart: jenkins-operator
    repoURL: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart
    targetRevision: 0.4.2
    helm:
      values: |
        jenkins:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true