apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-operator
  source:
    repoURL: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart
    chart: jenkins-operator
    targetRevision: 0.4.3
    helm:
      values: |
        jenkins:
          namespace: jenkins-operator
          # image: nicosto75/jenkins:2.263.4-1
          basePlugins:
            - name: kubernetes
              version: "1.29.2"
            - name: workflow-job
              version: "2.40"
            - name: workflow-aggregator
              version: "2.6"
            - name: git
              version: "4.7.0"
            - name: job-dsl
              version: "1.77"
            - name: configuration-as-code
              version: "1.47"
            - name: kubernetes-credentials-provider
              version: "0.18-1"

          plugins:
            - name: prometheus
              version: "2.0.9"
            - name: credentials
              version: "2.3.17"
            - name: plain-credentials
              version: "1.7"
            - name: dependency-track
              version: "3.1.1"
            - name: pipeline-utility-steps
              version: "2.7.1"

          seedJobs:
            - id: jenkins-operator
              targets: "jobs/*.jenkins"
              description: "Jenkins Operator repository"
              repositoryBranch: main
              repositoryUrl: https://github.com/nicosto/jenkins-seed.git

          resources:
            limits:
              cpu: 1500m
              memory: 3Gi
            requests:
              cpu: 1
              memory: 500Mi

          backup:
            pvc:
              className: "local-path"


  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true