apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  project: default
  source:
    chart: vault-operator
    # helm:
    #   values: |
    repoURL: https://kubernetes-charts.banzaicloud.com
    targetRevision: 1.11.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true