argo-cd:
  installCRDs: false
  global:
    image:
      tag: v1.8.4
  dex:
    enabled: false
  server:
    # extraArgs:
    #   - --insecure
    ingress:
      enabled: true
      hosts:
        - argocd.k3s.zremal.org
